services:
    notification.type.bookmark:
        class: replyPUSH\replybyemail\notification\type\bookmark
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - @replyPUSH.replybyemail.utility
        tags:
            - { name: notification.type }
            
    notification.type.post:
        class: replyPUSH\replybyemail\notification\type\post
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - @replyPUSH.replybyemail.utility
        tags:
            - { name: notification.type }
            
    notification.type.quote:
        class: replyPUSH\replybyemail\notification\type\quote
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - @replyPUSH.replybyemail.utility
        tags:
            - { name: notification.type }
            
    notification.type.topic:
        class: replyPUSH\replybyemail\notification\type\topic
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - @replyPUSH.replybyemail.utility
        tags:
            - { name: notification.type }
            
    notification.type.pm:
        class: replyPUSH\replybyemail\notification\type\pm
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
            - @replyPUSH.replybyemail.utility
        tags:
            - { name: notification.type }
            
    notification.helper.messenger:
        class: replyPUSH\replybyemail\helper\messenger
        arguments:
            - @config
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @ext.manager
        
    notification.method.email:
        class: replyPUSH\replybyemail\notification\method\reply_notification
        scope: prototype
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @notification.helper.messenger
            - @replyPUSH.replybyemail.model
            - @replyPUSH.replybyemail.utility
            - %core.root_path%
            - %core.php_ext%
            
        tags:
            - { name: notification.method }
