replybyemail_notify_ping:
    path: /replypush/ping/{uri}
    defaults: { _controller: replyPUSH.replybyemail.notify_controller:ping }

replybyemail_notify:
    path: /replypush/{uri}
    defaults: { _controller: replyPUSH.replybyemail.notify_controller:process_incoming_notification }
