imports:
    - { resource: overides.yml }

services:
    replyPUSH.replybyemail.reply_push:
        class: replyPUSH\replybyemail\library\ReplyPush
        
    replyPUSH.replybyemail.model:
        class: replyPUSH\replybyemail\model\rp_model
        arguments:
            - @dbal.conn
            - @replyPUSH.replybyemail.utility
            - %tables.notification_types%
            - %core.table_prefix%

    replyPUSH.replybyemail.notify_controller:
        class: replyPUSH\replybyemail\controller\notify_controller
        arguments:
            - @user
            - @config
            - @dbal.conn
            - @replyPUSH.replybyemail.utility
            - @notification.helper.messenger
            - @replyPUSH.replybyemail.model
            - %tables.notification_types%
            - %core.root_path%
            - %core.php_ext%

    replyPUSH.replybyemail.utility:
        class: replyPUSH\replybyemail\helper\utility
        arguments:
            - @user
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @cache
            - @log
            - %core.root_path%
            - %core.php_ext%

    replyPUSH.replybyemail.listener:
        class: replyPUSH\replybyemail\event\listener
        arguments:
            - @config
            - @template
            - @user
            - @auth
            - @replyPUSH.replybyemail.utility
            - @symfony_request
            - @controller.helper
            - %core.adm_relative_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    replyPUSH.replybyemail.acp_listener:
        class: replyPUSH\replybyemail\event\acp_listener
        arguments:
            - @config
            - @template
            - @user
            - @controller.helper
            - @replyPUSH.replybyemail.utility
            - %core.table_prefix%
        tags:
            - { name: event.listener }

